export const buttons = [
  { value: 'MC', type: 'memory' },
  { value: 'MR', type: 'memory' },
  { value: 'M-', type: 'memory' },
  { value: 'M+', type: 'memory' },
  { value: 'C', type: 'operator' },
  { value: 'MAGIC', type: 'memory' },
  { value: 'ROUND', type: 'operator' },
  { value: '/', type: 'operator' },
  { value: 7, type: 'number' },
  { value: 8, type: 'number' },
  { value: 9, type: 'number' },
  { value: 'x', type: 'operator' },
  { value: 4, type: 'number' },
  { value: 5, type: 'number' },
  { value: 6, type: 'number' },
  { value: '-', type: 'operator' },
  { value: 1, type: 'number' },
  { value: 2, type: 'number' },
  { value: 3, type: 'number' },
  { value: 0, type: 'number' },
  { value: '.', type: 'number' },
  { value: '=', type: 'operator' },
  { value: '+', type: 'operator' },
];
